[test]
dataset = NYtimes
k = 10
distance = cosine
method = NMSLIBHNSW

[method]
# M es el nr de conexiones del grafo. Mas M, más recall, más memoria
# Por defecto 32
M = 32
# efConstruction es el parametros de búsqueda en la construcción. Más efConstruction, más recall, más tiempo de indexación
# Lo habitual es 40-200
efConstruction = 40
# efSearch es el parámetro de búsqueda en la query. Más ef, más recall, más tiempo de consulta
# Por defecto 16
efSearch = 16

# post son heurísticas. 0 es sin heurística (más rápido, menor calidad). 2 es más cuidadoso (mejor recall)
post = 0
# Debe estar a true si es haversine y me lo da en grados. Else, False.
coords_in_degrees = False
